version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: conferences
      POSTGRES_USER: conferences_admin
      POSTGRES_PASSWORD: conferences_admin
    ports:
      - "5432:5432"
    volumes:
      - ./sql_initialisation/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
      - ./sql_initialisation/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql